//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2TomaszZawadzkiZadDom6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        public int TemplateId { get; set; }
        public string Website { get; set; }
        public string Content { get; set; }
        public string Level { get; set; }
        public string Logo { get; set; }
    }
}
